language: java

jdk: openjdk8

addons:
   sonarcloud:
      organization: "cosimogiani"
      token: $SONAR_TOKEN

install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
     - mvn -f com.prova.github/pom.xml -Pjacoco clean verify sonar:sonar