language: java

dist: xenial

jdk: openjdk8

services:
- docker
- xvfb

addons:
sonarcloud:
organization: "cosimogiani"

install: true

cache:
directories:
- $HOME/.m2
- $HOME/.sonar/cache

script:
- mvn -f com.prova.github/pom.xml clean verify -Pjacoco coveralls:report sonar:sonar